import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/theme-provider";
import Navbar from "@/components/template/Navbar";
import Command from "@/components/template/Command";
import Footer from "@/components/template/Footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${openSans.className} !p-0  w-2/3 !mx-auto antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<header>
						<Navbar />
					</header>
					{children}
					<Footer />
					<Command />
				</ThemeProvider>
			</body>
		</html>
	);
}
